# THIS IS THE NETWORK CONFIG OF THE HOST
network:
  version: 2
  ethernets:
    ens18:
      addresses:
      - 192.168.1.3/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.4, 8.8.8.8]
        search:
        - stam.lan
