# THIS IS THE NETWORK CONFIG OF THE HOST
network:
  version: 2
  ethernets:
    ens18:
      dhcp4: no
      addresses:
      - 192.168.1.4/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: 192.168.1.3
        search: []